# Generated by Django 5.2.8 on 2025-12-11 06:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Titre', max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(upload_to='banners/')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'banner',
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('first_title', models.CharField(blank=True, max_length=200, null=True)),
                ('second_title', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(upload_to='gallery/')),
                ('image_name', models.CharField(blank=True, max_length=255, null=True)),
                ('image_subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('button_text', models.CharField(blank=True, max_length=100, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'gallery_image',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=32, verbose_name='Nom de la page')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('escription', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'page',
            },
        ),
        migrations.CreateModel(
            name='ParagraphSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle_title', models.CharField(blank=True, max_length=200, null=True)),
                ('second_title', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='paragraph_sections/')),
                ('little_image', models.ImageField(blank=True, null=True, upload_to='paragraph_sections/')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('daten', models.DateTimeField(blank=True, null=True)),
                ('message', models.IntegerField(blank=True, null=True)),
                ('vue', models.CharField(blank=True, max_length=5, null=True)),
                ('job', models.CharField(blank=True, max_length=100, null=True)),
                ('button', models.CharField(blank=True, max_length=100, null=True)),
                ('adressage', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('text_button', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'paragraphe_section',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=32, verbose_name='Nom de la section')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('template', models.CharField(blank=True, max_length=255, verbose_name='nom de la section sans le html')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image de la section')),
            ],
            options={
                'db_table': 'section',
            },
        ),
        migrations.CreateModel(
            name='ServicesBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'services_block',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(blank=True, max_length=255, null=True)),
                ('sous_titre', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='sliders/')),
                ('video', models.FileField(blank=True, null=True, upload_to='sliders/videos/')),
                ('est_actif', models.BooleanField(default=True)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('transition', models.CharField(choices=[('fade', 'Fondu'), ('zoomout', 'Zoom arrière'), ('slideleft', 'Glisser à gauche'), ('slideright', 'Glisser à droite')], default='fade', max_length=50)),
                ('vitesse', models.PositiveIntegerField(default=1500, help_text='Durée de la transition du slide en millisecondes (ex: 2000 = 2 secondes).')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Slide',
                'verbose_name_plural': 'Slides',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Titre', max_length=100)),
                ('first_title', models.CharField(default='Texte par défaut', max_length=200)),
                ('second_title', models.CharField(default='Texte par défaut', max_length=100)),
                ('name', models.CharField(default='Texte par défaut', max_length=200)),
                ('job', models.CharField(default='Texte par défaut', max_length=200)),
                ('position', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='team/')),
                ('twitter', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('dribbble', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('behance', models.URLField(blank=True, null=True)),
            ],
            options={
                'db_table': 'team_member',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='PageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.PositiveIntegerField(verbose_name='Ordre dans la page')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.page', verbose_name='Page hôte')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.section', verbose_name='Section incluse')),
            ],
            options={
                'db_table': 'page_section',
                'ordering': ['ordre'],
                'unique_together': {('page', 'ordre'), ('page', 'section')},
            },
        ),
        migrations.AddField(
            model_name='page',
            name='sections',
            field=models.ManyToManyField(related_name='pages', through='website.PageSection', to='website.section'),
        ),
        migrations.CreateModel(
            name='SliderLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_layer', models.CharField(choices=[('text', 'Texte (Titre, paragraphe'), ('button', 'Bouton (Lien cliquable)'), ('shape', 'Forme (Arrière-plan, couleur)')], default='text', max_length=20)),
                ('contenu', models.TextField(blank=True, help_text='Le contenu du calque (texte du titre ou étiquette du bouton', null=True, verbose_name='Texte Affiché')),
                ('lien', models.URLField(blank=True, help_text="L'adresse vers laquelle le calque redirige (pour les boutons).", null=True, verbose_name='Lien Cliquable (URL)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='slider_layers/')),
                ('x', models.CharField(choices=[('left', 'Gauche'), ('center', 'Centre'), ('right', 'Droite')], default='center', max_length=50, verbose_name="Alignement Horizontal (centre l'élément)")),
                ('y', models.CharField(choices=[('top', 'Haut'), ('middle', 'Milieu'), ('bottom', 'Bas')], default='middle', max_length=50, verbose_name="Alignement Vertical (centre l'élément)")),
                ('decalage_horizontal', models.IntegerField(default=0, help_text="Déplacement en pixels par rapport à l'alignement X. Positif pour aller à droite, négatif pour aller à gauche.")),
                ('decalage_vertical', models.IntegerField(default=0, help_text="Déplacement en pixels par rapport à l'alignement Y. Utilisez un nombre négatif (ex: -70) pour monter, positif (ex: 50) pour descendre. C'est essentiel pour empiler les éléments !")),
                ('type_animation', models.CharField(choices=[('fade', 'Fondu'), ('fade-up', 'Fondu vers le haut'), ('fade-down', 'Fondu vers le bas'), ('slide-left', 'Glisser à gauche'), ('slide-right', 'Glisser à droite'), ('zoom-in', 'Zoom avant')], default='fade', max_length=50)),
                ('duree', models.PositiveIntegerField(default=2000, help_text="Durée de l'animation d'entrée en millisecondes.", validators=[django.core.validators.MinValueValidator(100)])),
                ('delai', models.PositiveIntegerField(default=1000, help_text="Temps en ms (millisecondes) avant que le calque n'apparaisse (1000 = 1 seconde).", validators=[django.core.validators.MinValueValidator(100)])),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('slide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layers', to='website.slider')),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=32, verbose_name='Nom de la menu')),
                ('url', models.CharField(max_length=255, verbose_name='URL de la menu')),
                ('ordre', models.IntegerField(verbose_name='Ordre de la menu')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.menu', verbose_name='Parent menu')),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Menus',
                'db_table': 'menu',
                'ordering': ['ordre'],
                'unique_together': {('parent', 'ordre')},
            },
        ),
    ]
