# Generated by Django 5.2.8 on 2025-12-11 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='animation',
            field=models.CharField(choices=[('fadeIn', 'Fade In'), ('fadeInUp', 'Fade In Up'), ('zoomIn', 'Zoom In'), ('bounceIn', 'Bounce In'), ('none', 'Aucune animation')], default='fadeIn', max_length=20),
        ),
        migrations.AddField(
            model_name='banner',
            name='animation_delay',
            field=models.CharField(choices=[('0s', '0 seconde'), ('0.5s', '0.5 seconde'), ('1s', '1 seconde'), ('1.5s', '1.5 seconde'), ('2s', '2 secondes')], default='0s', max_length=5),
        ),
    ]
