# Generated by Django 4.2.26 on 2025-11-14 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_teammember'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image de la section'),
        ),
        migrations.AddField(
            model_name='section',
            name='template',
            field=models.CharField(blank=True, max_length=255, verbose_name='nom de la section sans le html'),
        ),
    ]
