# Generated by Django 5.2.8 on 2025-12-11 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_banner_animation_banner_animation_delay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='escription',
        ),
    ]
