# Generated by Django 5.2.8 on 2025-11-20 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_section_image_section_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=200, null=True)),
                ('background_image', models.ImageField(upload_to='banners/')),
                ('animation', models.CharField(default='fadeInUp', max_length=50)),
                ('animation_delay', models.IntegerField(default=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
