# Generated by Django 5.2.8 on 2025-12-11 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_remove_page_escription'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='section',
            field=models.CharField(choices=[('awards', 'Awards'), ('gallery', 'Our Gallery'), ('shopping', 'Start Shopping With Us')], default='awards', max_length=20),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='button_text',
            field=models.CharField(blank=True, help_text="bouton sur l'image", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='first_title',
            field=models.CharField(blank=True, help_text='Sous titre', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image_name',
            field=models.CharField(blank=True, help_text="nom sur l'image", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image_subtitle',
            field=models.CharField(blank=True, help_text="sous titre sur l'image", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='second_title',
            field=models.CharField(blank=True, help_text='petite description', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='title',
            field=models.CharField(blank=True, help_text='titre de la section', max_length=200, null=True),
        ),
    ]
