# Generated by Django 5.2.8 on 2025-12-11 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_galleryimage_section_alter_galleryimage_button_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(blank=True, choices=[('awards', 'Awards'), ('gallery', 'Our Gallery'), ('shopping', 'Start Shopping With Us')], default='awards', max_length=20, null=True)),
                ('title', models.CharField(blank=True, help_text='Titre de la section', max_length=200, null=True)),
                ('first_title', models.CharField(blank=True, help_text='Sous-titre', max_length=200, null=True)),
                ('second_title', models.CharField(blank=True, help_text='Petite description', max_length=200, null=True)),
            ],
            options={
                'db_table': 'block_title',
            },
        ),
        migrations.RemoveField(
            model_name='galleryimage',
            name='first_title',
        ),
        migrations.RemoveField(
            model_name='galleryimage',
            name='second_title',
        ),
        migrations.RemoveField(
            model_name='galleryimage',
            name='section',
        ),
        migrations.RemoveField(
            model_name='galleryimage',
            name='title',
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='button_text',
            field=models.CharField(blank=True, help_text="Bouton sur l'image", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image_name',
            field=models.CharField(blank=True, help_text="Nom sur l'image", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image_subtitle',
            field=models.CharField(blank=True, help_text="Sous-titre sur l'image", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='block',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='website.blocktitle'),
        ),
    ]
