# Generated by Django 5.2.8 on 2025-11-27 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_banner'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='page',
            table='page',
        ),
    ]
