# Generated by Django 5.2.8 on 2025-11-27 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_page_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='banner',
            table='banner',
        ),
        migrations.AlterModelTable(
            name='menu',
            table='menu',
        ),
        migrations.AlterModelTable(
            name='pagesection',
            table='page_section',
        ),
        migrations.AlterModelTable(
            name='section',
            table='section',
        ),
        migrations.AlterModelTable(
            name='teammember',
            table='team_member',
        ),
    ]
