# Generated by Django 5.2.8 on 2025-12-11 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_blocktitle_remove_galleryimage_first_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paragraphsection',
            name='section_type',
            field=models.CharField(choices=[('since', 'Since'), ('sayor', 'Sayor'), ('testimonial', 'Testimonial'), ('connect', 'Connect'), ('stay_informed', 'Stay Informed')], default='since', help_text='Choisir le type de section', max_length=20),
        ),
    ]
