# Generated by Django 5.2.8 on 2025-11-28 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_banner_table_alter_menu_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('first_title', models.CharField(blank=True, max_length=200, null=True)),
                ('second_title', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(upload_to='gallery/')),
                ('image_name', models.CharField(blank=True, max_length=255, null=True)),
                ('image_subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('button_text', models.CharField(blank=True, max_length=100, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'gallery_image',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ParagraphSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle_title', models.CharField(blank=True, max_length=200, null=True)),
                ('second_title', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='paragraph_sections/')),
                ('little_image', models.ImageField(blank=True, null=True, upload_to='paragraph_sections/')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('daten', models.DateTimeField(blank=True, null=True)),
                ('message', models.IntegerField(blank=True, null=True)),
                ('vue', models.CharField(blank=True, max_length=5, null=True)),
                ('job', models.CharField(blank=True, max_length=100, null=True)),
                ('button', models.CharField(blank=True, max_length=100, null=True)),
                ('adressage', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('text_button', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'paragraphe_section',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ServicesBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'services_block',
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='teammember',
            name='first_title',
            field=models.CharField(default='Texte par défaut', max_length=200),
        ),
        migrations.AddField(
            model_name='teammember',
            name='job',
            field=models.CharField(default='Texte par défaut', max_length=200),
        ),
        migrations.AddField(
            model_name='teammember',
            name='second_title',
            field=models.CharField(default='Texte par défaut', max_length=100),
        ),
        migrations.AddField(
            model_name='teammember',
            name='title',
            field=models.CharField(default='Titre', max_length=100),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(default='Titre', max_length=200),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='name',
            field=models.CharField(default='Texte par défaut', max_length=200),
        ),
    ]
