# Generated by Django 5.2.8 on 2025-12-11 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_paragraphsection_section_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParagraphTitleAndManyElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Titre principal', max_length=200)),
                ('subtitle', models.CharField(blank=True, help_text='Sous-titre', max_length=200, null=True)),
                ('description', models.TextField(blank=True, help_text='Description longue', null=True)),
                ('name', models.CharField(default='Texte par défaut', max_length=200)),
                ('job', models.CharField(default='Texte par défaut', max_length=200)),
                ('position', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='image/')),
                ('twitter', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('dribbble', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('behance', models.URLField(blank=True, null=True)),
                ('button', models.CharField(blank=True, help_text='Text du bouton principal', max_length=100, null=True)),
                ('montant', models.IntegerField(blank=True, null=True)),
                ('avantage_prix', models.CharField(blank=True, max_length=200, null=True)),
                ('button_text', models.CharField(blank=True, help_text='Description du bouton principal', max_length=200, null=True)),
                ('order', models.PositiveIntegerField(blank=True, default=0, help_text="Ordre d'affichage", null=True)),
            ],
            options={
                'verbose_name': 'Paragraph Title & Element',
                'verbose_name_plural': 'Paragraph Titles & Elements',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TitleSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Titre principal', max_length=200)),
                ('subtitle', models.CharField(blank=True, help_text='Sous-titre', max_length=200, null=True)),
                ('description', models.TextField(blank=True, help_text='Description longue', null=True)),
            ],
            options={
                'verbose_name': 'Section Titre',
                'verbose_name_plural': 'Sections Titre',
            },
        ),
        migrations.DeleteModel(
            name='TeamMember',
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['id']},
        ),
        migrations.AlterUniqueTogether(
            name='menu',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='paragraphsection',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paragraphsection',
            name='section_type',
            field=models.CharField(choices=[('since', 'Since'), ('connect', 'Connect')], default='since', help_text='Choisir le type de section', max_length=20),
        ),
        migrations.AlterField(
            model_name='servicesblock',
            name='icon',
            field=models.ImageField(blank=True, help_text='Icône associée à la section', null=True, upload_to='paragraph_sections/icons/'),
        ),
        migrations.AlterModelTable(
            name='menu',
            table='team_member',
        ),
        migrations.AddField(
            model_name='paragraphtitleandmanyelement',
            name='section',
            field=models.ForeignKey(help_text='Choisir la section à laquelle ce paragraphe appartient', on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='website.paragraphsection'),
        ),
    ]
