# Generated by Django 5.2.8 on 2025-12-11 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_paragraphtitleandmanyelement_titlesection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='titlesection',
            name='section_type',
            field=models.CharField(choices=[('testimonials', 'Testimonials'), ('cheap_pricing', 'Cheap Pricing'), ('our_team', 'Our Team'), ('savor_savings', 'Savor the Savings'), ('stay_informed', 'Stay Informed')], default='testimonials', help_text='Choisir le type de section', max_length=20),
        ),
        migrations.AlterField(
            model_name='paragraphtitleandmanyelement',
            name='button',
            field=models.CharField(blank=True, help_text='Texte du bouton principal', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paragraphtitleandmanyelement',
            name='button_text',
            field=models.CharField(blank=True, help_text='Texte supplémentaire du bouton', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='paragraphtitleandmanyelement',
            name='section',
            field=models.ForeignKey(help_text='Choisir la section à laquelle ce paragraphe appartient', on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='website.titlesection'),
        ),
    ]
