# Generated by Django 5.2.8 on 2025-12-11 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_titlesection_section_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paragraphtitleandmanyelement',
            name='button_text',
            field=models.TextField(blank=True, help_text='Texte supplémentaire du bouton', null=True),
        ),
        migrations.AlterField(
            model_name='paragraphtitleandmanyelement',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paragraphtitleandmanyelement',
            name='title',
            field=models.CharField(blank=True, help_text='Titre ', max_length=200, null=True),
        ),
    ]
