# Generated by Django 5.2.8 on 2025-12-11 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_alter_paragraphtitleandmanyelement_button_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paragraphtitleandmanyelement',
            name='image_caroussel',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='paragraphtitleandmanyelement',
            name='title',
            field=models.CharField(blank=True, default='Titre par défaut', help_text='Titre ', max_length=200, null=True),
        ),
    ]
