# Generated by Django 5.2.8 on 2025-12-11 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_paragraphtitleandmanyelement_image_caroussel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paragraphtitleandmanyelement',
            name='description_carrouselle',
            field=models.TextField(blank=True, help_text='Description pour le commentaire defilnt', null=True),
        ),
    ]
