# Generated by Django 5.2.8 on 2025-12-11 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_paragraphtitleandmanyelement_description_carrouselle'),
    ]

    operations = [
        migrations.AddField(
            model_name='paragraphtitleandmanyelement',
            name='adresse',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
