# Generated by Django 5.2.8 on 2025-12-11 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_paragraphtitleandmanyelement_adresse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paragraphtitleandmanyelement',
            name='description',
        ),
        migrations.RemoveField(
            model_name='paragraphtitleandmanyelement',
            name='image',
        ),
        migrations.AddField(
            model_name='titlesection',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
