# Generated by Django 5.2.8 on 2025-12-11 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_remove_paragraphtitleandmanyelement_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paragraphtitleandmanyelement',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='paragraphtitleandmanyelement',
            name='title',
        ),
    ]
