# Generated by Django 5.2.8 on 2025-12-11 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_remove_paragraphtitleandmanyelement_subtitle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paragraphtitleandmanyelement',
            name='job',
            field=models.CharField(blank=True, default='Texte par défaut', max_length=200, null=True),
        ),
    ]
